### ISSUE TITLE
运行predict_bert.py时报错TypeError: add_weight() got multiple values for argument 'name'怎么解决呀

### ISSUE THREAD

**Issue by Phoenix-Qiu** [MenglinLu/Chinese-clinical-NER#14]
Traceback (most recent call last):
  File "/home/customer/qlf/code/Chinese-clinical-NER/bert_bilstm_crf/predict_bert.py", line 19, in <module>
    model=Bert_ner(config_path,checkpoint_path,dict_path).model_build_bert_crf()
  File "/home/customer/qlf/code/Chinese-clinical-NER/bert_bilstm_crf/bert_ner.py", line 54, in model_build_bert_crf
    output = crf(x)
  File "/home/customer/anaconda3/envs/qlf_dl/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 926, in __call__
    input_list)
  File "/home/customer/anaconda3/envs/qlf_dl/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1098, in _functional_construction_call
    self._maybe_build(inputs)
  File "/home/customer/anaconda3/envs/qlf_dl/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 2643, in _maybe_build
    self.build(input_shapes)  # pylint:disable=not-callable
  File "/home/customer/qlf/code/Chinese-clinical-NER/bert_bilstm_crf/crf_layer.py", line 203, in build
    constraint=self.kernel_constraint)
TypeError: add_weight() got multiple values for argument 'name'

Process finished with exit code 1
（来自代码小白的抓狂）
求大佬们帮忙解决啊~~~

**Comment by zhazhab** [comment]
+1 碰到这个问题，这个估计和库的版本有关，可能得问一下博主了
